import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

// All configuration lives in config.json (gitignored), generated by
// config-gen.sh. There are deliberately no environment variables.

export interface GithubConfig {
  /** The GitHub CLI to shell out to. It brings its own auth, so no token here. */
  command: string;
  /** Explicit repos to track, as "owner/name". */
  repos: string[];
  /** Orgs whose repos are all tracked, resolved to repo names at sync time. */
  orgs?: string[];
  /** How far back the first sync reaches. Later syncs are incremental. */
  backfillDays?: number;
}

export interface LlmConfig {
  provider: string;
  baseUrl: string;
  model: string;
}

export interface SyncConfig {
  intervalMinutes?: number;
}

export interface Config {
  github: GithubConfig;
  llm: LlmConfig;
  sync?: SyncConfig;
  server?: {
    port?: number;
    /** There is no auth — the default bind is loopback. Widening this is only
     * safe behind something that authenticates (SSH tunnel, reverse proxy). */
    host?: string;
  };
}

const CONFIG_PATH = resolve(process.cwd(), "config.json");

export function loadConfig(): Config {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(
      `config.json not found at ${CONFIG_PATH}.\n` +
        "Run ./config-gen.sh to generate it.",
    );
  }
  try {
    const config = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Config;
    config.github ??= { command: "gh", repos: [] };
    config.github.command ||= "gh";
    config.github.repos ??= [];
    config.github.orgs ??= [];
    config.github.backfillDays ??= 90;
    config.llm ??= {
      provider: "vllm",
      baseUrl: "http://localhost:8000/v1",
      model: "default",
    };
    config.sync ??= {};
    config.sync.intervalMinutes ??= 30;
    return config;
  } catch (err) {
    throw new Error(`Failed to parse config.json: ${(err as Error).message}`);
  }
}
